{"name": "Check human search in table", "status": "failed", "statusDetails": {"message": "AssertionError: the person was not found in the table\nassert '79989' in ['Cierra', 'Vega', '39', 'cierra@example.com', '10000', 'Insurance']", "trace": "self = <elements_test.TestElements.TestWebTable object at 0x000001C26C5ED5D0>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"28939497fc4055ea6adf8e4e4b44b4be\")>\n\n    @allure.title('Check human search in table')\n    def test_web_table_search_person(self, driver):\n        web_table_page = WebTablePage(driver, 'https://demoqa.com/webtables')\n        web_table_page.open()\n        key_word = web_table_page.add_new_person()[random.randint(0, 5)]\n        web_table_page.search_some_person(key_word)\n        table_result = web_table_page.check_search_person()\n        # print(key_word)\n        # print(table_result)\n>       assert key_word in table_result, \"the person was not found in the table\"\nE       AssertionError: the person was not found in the table\nE       assert '79989' in ['Cierra', 'Vega', '39', 'cierra@example.com', '10000', 'Insurance']\n\ntests\\elements_test.py:79: AssertionError"}, "start": 1685655623599, "stop": 1685655644539, "uuid": "5dc76d17-dbe1-474b-8659-ef0861bbfab8", "historyId": "d97e9261471c2d21f2d5fc9c2870cb99", "testCaseId": "d97e9261471c2d21f2d5fc9c2870cb99", "fullName": "tests.elements_test.TestWebTable#test_web_table_search_person", "labels": [{"name": "suite", "value": "Elements"}, {"name": "feature", "value": "WebTable"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestElements"}, {"name": "host", "value": "LAPTOP-OHPH4I30"}, {"name": "thread", "value": "34500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.elements_test"}]}