{"name": "Check human search in table", "status": "failed", "statusDetails": {"message": "AssertionError: the person was not found in the table\nassert 'ziminostap@example.net' in ['Cierra', 'Vega', '39', 'cierra@example.com', '10000', 'Insurance']", "trace": "self = <elements_test.TestElements.TestWebTable object at 0x00000242C5D792A0>, driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6e5874dcf6c93256849e660d20d0ffde\")>\n\n    @allure.title('Check human search in table')\n    def test_web_table_search_person(self, driver):\n        web_table_page = WebTablePage(driver, 'https://demoqa.com/webtables')\n        web_table_page.open()\n        key_word = web_table_page.add_new_person()[random.randint(0, 5)]\n        web_table_page.search_some_person(key_word)\n        table_result = web_table_page.check_search_person()\n        # print(key_word)\n        # print(table_result)\n>       assert key_word in table_result, \"the person was not found in the table\"\nE       AssertionError: the person was not found in the table\nE       assert 'ziminostap@example.net' in ['Cierra', 'Vega', '39', 'cierra@example.com', '10000', 'Insurance']\n\ntests\\elements_test.py:79: AssertionError"}, "start": 1685823958443, "stop": 1685823967221, "uuid": "2512fcc7-e7ef-46a0-a8eb-6a46c85a77c3", "historyId": "d97e9261471c2d21f2d5fc9c2870cb99", "testCaseId": "d97e9261471c2d21f2d5fc9c2870cb99", "fullName": "tests.elements_test.TestWebTable#test_web_table_search_person", "labels": [{"name": "feature", "value": "WebTable"}, {"name": "suite", "value": "Elements"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestElements"}, {"name": "host", "value": "LAPTOP-OHPH4I30"}, {"name": "thread", "value": "35716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.elements_test"}]}